// Sources/EdgeRumCore/Context/SessionContext.swift
//
// Holds the active session triple — `session.id`, `session.start_time`,
// `session.sequence`. Persistence is `SessionStore`-driven: F3 ships
// `InMemorySessionStore` and F4 layers on `UserDefaultsSessionStore`
// (suite `com.edge.rum.session`) without changing this type.
//
// IDs are generated by `SecRandomCopyBytes(8)` formatted as 16 hex
// chars per CLAUDE.md "Session and ID rules". `UUID()` is NOT used —
// its hex section is 128 bits and breaks the format regex the
// backend dispatcher relies on.
//
// Session lifecycle:
//   - First `recordEvent` after `start()` creates a session if none
//     exists, or rotates if the last-active timestamp is older than
//     30 minutes (`idle`) or the session is 4 hours old
//     (`max_duration`).
//   - `session.sequence` increments on every successful transport ack
//     — F4 calls `incrementSequence()` after a 2xx response.
//   - `session.start_time` is captured at creation and never updates.
//
// Refs: PLAN-iOS.md §F3/T3.3, §F4/T4.4; CLAUDE.md "Session and ID
//       rules" and "Session lifecycle".
//

import Foundation
import Security

public struct SessionState: Sendable, Hashable, Codable {
    public var id: String
    public var startTime: Date
    public var sequence: Int
    public var lastActiveAt: Date

    public init(id: String, startTime: Date, sequence: Int, lastActiveAt: Date) {
        self.id = id
        self.startTime = startTime
        self.sequence = sequence
        self.lastActiveAt = lastActiveAt
    }
}

/// Pluggable storage so F4 can layer UserDefaults persistence on top
/// of the in-memory default that ships in F3.
public protocol SessionStore: Sendable {
    func load() -> SessionState?
    func save(_ state: SessionState)
}

public final class InMemorySessionStore: SessionStore, @unchecked Sendable {
    private let lock = NSLock()
    private var _state: SessionState?

    public init() {}

    public func load() -> SessionState? {
        lock.lock(); defer { lock.unlock() }
        return _state
    }

    public func save(_ state: SessionState) {
        lock.lock(); _state = state; lock.unlock()
    }
}

/// Manages the live session state. Thread-safe — every public method
/// is guarded by an internal lock. Pass the same `clock` you give the
/// `Recorder` so test fixtures stay deterministic.
public final class SessionManager: @unchecked Sendable {

    /// 30 minutes of inactivity rotates the session.
    public static let idleRotationInterval: TimeInterval = 30 * 60

    /// A session older than 4 hours rotates on the next touch, so a
    /// continuously-used app still ends sessions (F29).
    public static let maxSessionDuration: TimeInterval = 4 * 60 * 60

    private let lock = NSLock()
    private let store: SessionStore
    private let clock: Clock
    private let randomBytes: () -> Data

    public init(
        store: SessionStore = InMemorySessionStore(),
        clock: Clock = SystemClock(),
        randomBytes: @escaping () -> Data = SessionManager.secureRandomBytes
    ) {
        self.store = store
        self.clock = clock
        self.randomBytes = randomBytes
    }

    /// Returns the current session state, creating a new one if no
    /// session exists, the last-active timestamp is older than
    /// `idleRotationInterval`, or the session is older than
    /// `maxSessionDuration`. Updates `lastActiveAt` to "now".
    /// `ended` carries the session this call ended and why (`idle` or
    /// `max_duration`); `nil` when nothing ended (first session).
    @discardableResult
    public func touch() -> (state: SessionState, rotated: Bool, ended: (state: SessionState, reason: String)?) {
        lock.lock(); defer { lock.unlock() }
        let now = clock.now
        var ended: (state: SessionState, reason: String)?
        if let existing = store.load() {
            if now.timeIntervalSince(existing.lastActiveAt) >= Self.idleRotationInterval {
                ended = (existing, "idle")
            } else if now.timeIntervalSince(existing.startTime) >= Self.maxSessionDuration {
                ended = (existing, "max_duration")
            } else {
                var updated = existing
                updated.lastActiveAt = now
                store.save(updated)
                return (updated, false, nil)
            }
        }
        let fresh = createSession(at: now)
        store.save(fresh)
        return (fresh, true, ended)
    }

    /// Increment the `session.sequence` counter — called by the
    /// transport layer after a 2xx response on a successful batch
    /// flush.
    public func incrementSequence() {
        lock.lock(); defer { lock.unlock() }
        guard var state = store.load() else { return }
        state.sequence += 1
        state.lastActiveAt = clock.now
        store.save(state)
    }

    public func currentState() -> SessionState? {
        lock.lock(); defer { lock.unlock() }
        return store.load()
    }

    // MARK: ID generation

    /// Default entropy source — `SecRandomCopyBytes(8)`. Exposed so
    /// tests can inject a deterministic byte sequence.
    public static func secureRandomBytes() -> Data {
        var bytes = [UInt8](repeating: 0, count: 8)
        let status = SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes)
        if status != errSecSuccess {
            // SecRandomCopyBytes failing is so unusual on iOS that
            // we'd rather log loudly than ship zero entropy. Fall
            // back to `arc4random_buf` which is also CSPRNG-backed.
            arc4random_buf(&bytes, bytes.count)
        }
        return Data(bytes)
    }

    private func createSession(at now: Date) -> SessionState {
        SessionState(
            id: Self.formatSessionId(epochMs: epochMillis(of: now), random: randomBytes()),
            startTime: now,
            sequence: 0,
            lastActiveAt: now
        )
    }

    /// `session_<epochMs>_<16 hex>_ios` — see CLAUDE.md "Session and
    /// ID rules".
    public static func formatSessionId(epochMs: Int64, random: Data) -> String {
        let hex = random.prefix(8).map { String(format: "%02x", $0) }.joined()
        let padded = hex.padding(toLength: 16, withPad: "0", startingAt: 0)
        return "session_\(epochMs)_\(padded)_ios"
    }

    private func epochMillis(of date: Date) -> Int64 {
        Int64(date.timeIntervalSince1970 * 1000)
    }
}

public extension SessionContextSnapshot {
    /// Convenience to write the wire keys.
    func write(into bag: inout AttributeBag) {
        bag.set("session.id", .string(id))
        bag.set("session.start_time", .string(WireDateFormatter.string(from: startTime)))
        bag.set("session.sequence", .int(sequence))
    }
}

/// Read-only view of the session triple for ContextProvider snapshots.
public struct SessionContextSnapshot: Sendable, Hashable {
    public let id: String
    public let startTime: Date
    public let sequence: Int

    public init(id: String, startTime: Date, sequence: Int) {
        self.id = id
        self.startTime = startTime
        self.sequence = sequence
    }

    public init(_ state: SessionState) {
        self.id = state.id
        self.startTime = state.startTime
        self.sequence = state.sequence
    }
}
