#!/usr/bin/env bash
#
# Tools/gen-version.sh
#
# Reads the SemVer string from the repo-root VERSION file and writes it
# into a generated Swift file containing one internal constant. The
# constant is consumed by EdgeRum.sdkVersion (which becomes the
# `sdk.version` attribute on every event) — PLAN-iOS.md §2.6, F1/T1.3.
#
# Usage:
#   gen-version.sh <output-swift-file>
#
# Invocation:
#   - Local manual: ./Tools/gen-version.sh Sources/EdgeRum/Generated/EdgeRumVersion.swift
#   - SwiftPM build plugin: Plugins/EdgeRumVersionPlugin (runs at every build)
#
# Idempotent: if the destination already contains the expected content,
# the file is left untouched so SwiftPM's incremental build is not
# invalidated.
#
# Validates that VERSION matches semver: MAJOR.MINOR.PATCH(-PRERELEASE)?

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "usage: $0 <output-swift-file>" >&2
    exit 2
fi

OUTPUT="$1"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION_FILE="${REPO_ROOT}/VERSION"

if [[ ! -f "${VERSION_FILE}" ]]; then
    echo "gen-version: VERSION file not found at ${VERSION_FILE}" >&2
    exit 1
fi

VERSION="$(head -n1 "${VERSION_FILE}" | tr -d '[:space:]')"

if [[ -z "${VERSION}" ]]; then
    echo "gen-version: VERSION file is empty" >&2
    exit 1
fi

# SemVer 2.0 (no build metadata in v1, but allow the +build suffix).
SEMVER_RE='^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$'
if ! [[ "${VERSION}" =~ ${SEMVER_RE} ]]; then
    echo "gen-version: '${VERSION}' is not a valid SemVer 2.0 version" >&2
    exit 1
fi

mkdir -p "$(dirname "${OUTPUT}")"

NEW_CONTENT="// This file is generated by Tools/gen-version.sh from the repo-root
// VERSION file via the SwiftPM EdgeRumVersionPlugin. Do not edit by hand —
// changes will be overwritten on the next build.

internal enum EdgeRumGeneratedVersion {
    /// SemVer string read from <repo-root>/VERSION at build time.
    internal static let string: String = \"${VERSION}\"
}
"

# Idempotency check via grep for the version line. Beats a full-file
# string compare which is fragile around trailing-newline semantics
# between `$(cat)` and bash heredocs. Keeps SwiftPM's incremental build
# cache valid by skipping the write when content is unchanged.
if [[ -f "${OUTPUT}" ]] \
    && grep -qF "let string: String = \"${VERSION}\"" "${OUTPUT}"; then
    exit 0
fi

printf '%s' "${NEW_CONTENT}" > "${OUTPUT}"
echo "gen-version: wrote ${OUTPUT} (version ${VERSION})"
